/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Database;
import model.Pendaftar;
import static assets.Warna.HOVERIN;
import static assets.Warna.HOVEROUT;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.*;
/**
 *
 * @author fauzanalfaraby
 */
public class FormPendataranKegiatan extends javax.swing.JFrame {
    
    private boolean validateInput(){
        //Validate nim 
        if (nimTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan NIM anda", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Validate nama 
        if (namaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan Nama anda", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Validate jenis kelamin
        if (jkbuttonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Pilih Jenis Kelamin anda", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        //Validate alamat
        if (alamatTextArea.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Alamat anda", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        //Validate email
        if (emailTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Email anda", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        //Validate email
        String email = emailTextField.getText();
        String emailPattern = nimTextField.getText() + "@stis.ac.id";
        if (!email.equals(emailPattern)) {
            JOptionPane.showMessageDialog(this, "Email harus dalam format 'nim@stis.ac.id'", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        //Validate no telephone
        if (tlpnTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan No.Telephone anda", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void clear_form(){
        namaKegiatanComboBox.setSelectedItem(this);
        nimTextField.setText("");
        namaTextField.setText("");
        jkbuttonGroup.clearSelection();
        tingkatComboBox.setSelectedIndex(0);
        alamatTextArea.setText("");
        emailTextField.setText("");
        tlpnTextField.setText("");
    }
    /**
     * Creates new form FormPendaftaran
     */
    public FormPendataranKegiatan() {
        initComponents();
        setResizable(true);
        
        setTitle("FutsalFusion | Form Pendaftaran kegiatan"); // Memberikan judul pada jendela
        
        // Mengatur ikon jendela
        ImageIcon icon = new ImageIcon("src/assets/logo fiks2.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaKegiatanLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        jkLabel = new javax.swing.JLabel();
        tingkatLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        tlpnLabel = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        emailTextField = new javax.swing.JTextField();
        tlpnTextField = new javax.swing.JTextField();
        hapusButton = new javax.swing.JButton();
        daftarButton = new javax.swing.JButton();
        tingkatComboBox = new javax.swing.JComboBox<>();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        namaKegiatanComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel1.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulir Pendaftaran");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo futsal.png"))); // NOI18N

        namaKegiatanLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaKegiatanLabel.setText("Nama kegiatan");

        nimLabel.setForeground(new java.awt.Color(255, 255, 255));
        nimLabel.setText("NIM");

        namaLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaLabel.setText("Nama");

        jkLabel.setForeground(new java.awt.Color(255, 255, 255));
        jkLabel.setText("Jenis Kelamin");

        tingkatLabel.setForeground(new java.awt.Color(255, 255, 255));
        tingkatLabel.setText("Tingkat");

        alamatLabel.setForeground(new java.awt.Color(255, 255, 255));
        alamatLabel.setText("Alamat");

        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");

        tlpnLabel.setForeground(new java.awt.Color(255, 255, 255));
        tlpnLabel.setText("No.Telepon");

        nimTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nimTextFieldKeyTyped(evt);
            }
        });

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        alamatTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(alamatTextArea);

        tlpnTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tlpnTextFieldKeyTyped(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusButtonMouseExited(evt);
            }
        });
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        daftarButton.setText("Daftar");
        daftarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daftarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                daftarButtonMouseExited(evt);
            }
        });
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        tingkatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jkbuttonGroup.add(lakiRadioButton);
        lakiRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        lakiRadioButton.setText("Laki-Laki");

        jkbuttonGroup.add(perempuanRadioButton);
        perempuanRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        perempuanRadioButton.setText("Perempuan");

        namaKegiatanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih kegiatan.....", "Fun Futsal", "Mini Soccer", "Bina Fisik", "Friendly Match Futsal" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaKegiatanLabel)
                            .addComponent(nimLabel)
                            .addComponent(namaLabel)
                            .addComponent(jkLabel)
                            .addComponent(tingkatLabel)
                            .addComponent(alamatLabel)
                            .addComponent(tlpnLabel)
                            .addComponent(emailLabel))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hapusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(daftarButton))
                            .addComponent(emailTextField)
                            .addComponent(lakiRadioButton)
                            .addComponent(perempuanRadioButton)
                            .addComponent(tingkatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(tlpnTextField)
                            .addComponent(namaKegiatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKegiatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaKegiatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nimLabel)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLabel)
                    .addComponent(lakiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perempuanRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tingkatLabel)
                    .addComponent(tingkatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlpnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlpnLabel))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarButton)
                    .addComponent(hapusButton))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        clear_form();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tlpnTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlpnTextFieldKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(!(Character.isDigit(ch))){
            evt.consume();
        }
    }//GEN-LAST:event_tlpnTextFieldKeyTyped

    private void nimTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nimTextFieldKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) || tlpnTextField.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_nimTextFieldKeyTyped

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // TODO add your handling code here:
        if (validateInput()){
            Pendaftar mhs = new Pendaftar();
            mhs.setNamaKegiatan(namaKegiatanComboBox.getSelectedItem().toString());
            mhs.setNim(nimTextField.getText());
            mhs.setNama(namaTextField.getText());
            if(lakiRadioButton.isSelected()){
                mhs.setJk("Laki-Laki");
            }
            if(perempuanRadioButton.isSelected()){
                mhs.setJk("Perempuan");
            }
            mhs.setTingkat(tingkatComboBox.getSelectedItem().toString());
            mhs.setAlamat(alamatTextArea.getText());
            mhs.setEmail(emailTextField.getText());
            mhs.setTlpn(tlpnTextField.getText());

            try{
                Database.getInstance().insertPendaftar(mhs);
                clear_form();
                JOptionPane.showMessageDialog(null, "Anda berhasil mendaftar");
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace(); // Cetak stack trace ke konsol untuk debugging
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void daftarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarButtonMouseEntered
        // TODO add your handling code here:
        daftarButton.setBackground(HOVERIN);
    }//GEN-LAST:event_daftarButtonMouseEntered

    private void daftarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarButtonMouseExited
        // TODO add your handling code here:
        daftarButton.setBackground(HOVEROUT);
    }//GEN-LAST:event_daftarButtonMouseExited

    private void hapusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusButtonMouseEntered
        // TODO add your handling code here:
        hapusButton.setBackground(HOVERIN);
    }//GEN-LAST:event_hapusButtonMouseEntered

    private void hapusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusButtonMouseExited
        // TODO add your handling code here:
        hapusButton.setBackground(HOVEROUT);
    }//GEN-LAST:event_hapusButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton daftarButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jkLabel;
    private javax.swing.ButtonGroup jkbuttonGroup;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JComboBox<String> namaKegiatanComboBox;
    private javax.swing.JLabel namaKegiatanLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> tingkatComboBox;
    private javax.swing.JLabel tingkatLabel;
    private javax.swing.JLabel tlpnLabel;
    private javax.swing.JTextField tlpnTextField;
    // End of variables declaration//GEN-END:variables
}
